const mockField = [
  [
    { value: null, isFixed: false, rowIndex: 0, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 0, colIndex: 1, notes: [] },
    { value: null, isFixed: false, rowIndex: 0, colIndex: 2, notes: [] },
    { value: 8, isFixed: true, rowIndex: 0, colIndex: 3, notes: [] },
    { value: 4, isFixed: true, rowIndex: 0, colIndex: 4, notes: [] },
    { value: null, isFixed: false, rowIndex: 0, colIndex: 5, notes: [] },
    { value: 2, isFixed: true, rowIndex: 0, colIndex: 6, notes: [] },
    { value: null, isFixed: false, rowIndex: 0, colIndex: 7, notes: [] },
    { value: null, isFixed: false, rowIndex: 0, colIndex: 8, notes: [] },
  ],
  [
    { value: null, isFixed: false, rowIndex: 1, colIndex: 0, notes: [] },
    { value: 1, isFixed: true, rowIndex: 1, colIndex: 1, notes: [] },
    { value: null, isFixed: false, rowIndex: 1, colIndex: 2, notes: [] },
    { value: 2, isFixed: true, rowIndex: 1, colIndex: 3, notes: [] },
    { value: 7, isFixed: true, rowIndex: 1, colIndex: 4, notes: [] },
    { value: 6, isFixed: true, rowIndex: 1, colIndex: 5, notes: [] },
    { value: 9, isFixed: true, rowIndex: 1, colIndex: 6, notes: [] },
    { value: 3, isFixed: true, rowIndex: 1, colIndex: 7, notes: [] },
    { value: 8, isFixed: true, rowIndex: 1, colIndex: 8, notes: [] },
  ],
  [
    { value: null, isFixed: false, rowIndex: 2, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 2, colIndex: 1, notes: [] },
    { value: null, isFixed: false, rowIndex: 2, colIndex: 2, notes: [] },
    { value: 9, isFixed: true, rowIndex: 2, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 2, colIndex: 4, notes: [] },
    { value: null, isFixed: false, rowIndex: 2, colIndex: 5, notes: [] },
    { value: 6, isFixed: true, rowIndex: 2, colIndex: 6, notes: [] },
    { value: null, isFixed: false, rowIndex: 2, colIndex: 7, notes: [] },
    { value: 4, isFixed: true, rowIndex: 2, colIndex: 8, notes: [] },
  ],
  [
    { value: null, isFixed: false, rowIndex: 3, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 3, colIndex: 1, notes: [] },
    { value: 7, isFixed: true, rowIndex: 3, colIndex: 2, notes: [] },
    { value: null, isFixed: false, rowIndex: 3, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 3, colIndex: 4, notes: [] },
    { value: 9, isFixed: true, rowIndex: 3, colIndex: 5, notes: [] },
    { value: null, isFixed: false, rowIndex: 3, colIndex: 6, notes: [] },
    { value: null, isFixed: false, rowIndex: 3, colIndex: 7, notes: [] },
    { value: 6, isFixed: true, rowIndex: 3, colIndex: 8, notes: [] },
  ],
  [
    { value: null, isFixed: false, rowIndex: 4, colIndex: 0, notes: [] },
    { value: 9, isFixed: true, rowIndex: 4, colIndex: 1, notes: [] },
    { value: 3, isFixed: true, rowIndex: 4, colIndex: 2, notes: [] },
    { value: null, isFixed: false, rowIndex: 4, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 4, colIndex: 4, notes: [] },
    { value: null, isFixed: false, rowIndex: 4, colIndex: 5, notes: [] },
    { value: null, isFixed: false, rowIndex: 4, colIndex: 6, notes: [] },
    { value: 8, isFixed: true, rowIndex: 4, colIndex: 7, notes: [] },
    { value: 2, isFixed: true, rowIndex: 4, colIndex: 8, notes: [] },
  ],
  [
    { value: 1, isFixed: true, rowIndex: 5, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 5, colIndex: 1, notes: [] },
    { value: null, isFixed: false, rowIndex: 5, colIndex: 2, notes: [] },
    { value: 6, isFixed: true, rowIndex: 5, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 5, colIndex: 4, notes: [] },
    { value: 2, isFixed: true, rowIndex: 5, colIndex: 5, notes: [] },
    { value: 4, isFixed: true, rowIndex: 5, colIndex: 6, notes: [] },
    { value: 9, isFixed: true, rowIndex: 5, colIndex: 7, notes: [] },
    { value: null, isFixed: false, rowIndex: 5, colIndex: 8, notes: [] },
  ],
  [
    { value: 8, isFixed: true, rowIndex: 6, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 1, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 2, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 3, notes: [] },
    { value: 6, isFixed: true, rowIndex: 6, colIndex: 4, notes: [] },
    { value: 4, isFixed: true, rowIndex: 6, colIndex: 5, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 6, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 7, notes: [] },
    { value: null, isFixed: false, rowIndex: 6, colIndex: 8, notes: [] },
  ],
  [
    { value: 5, isFixed: true, rowIndex: 7, colIndex: 0, notes: [] },
    { value: 2, isFixed: true, rowIndex: 7, colIndex: 1, notes: [] },
    { value: 6, isFixed: true, rowIndex: 7, colIndex: 2, notes: [] },
    { value: 3, isFixed: true, rowIndex: 7, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 7, colIndex: 4, notes: [] },
    { value: null, isFixed: false, rowIndex: 7, colIndex: 5, notes: [] },
    { value: null, isFixed: false, rowIndex: 7, colIndex: 6, notes: [] },
    { value: 4, isFixed: true, rowIndex: 7, colIndex: 7, notes: [] },
    { value: 1, isFixed: true, rowIndex: 7, colIndex: 8, notes: [] },
  ],
  [
    { value: null, isFixed: false, rowIndex: 8, colIndex: 0, notes: [] },
    { value: null, isFixed: false, rowIndex: 8, colIndex: 1, notes: [] },
    { value: 4, isFixed: true, rowIndex: 8, colIndex: 2, notes: [] },
    { value: 5, isFixed: true, rowIndex: 8, colIndex: 3, notes: [] },
    { value: null, isFixed: false, rowIndex: 8, colIndex: 4, notes: [] },
    { value: 1, isFixed: true, rowIndex: 8, colIndex: 5, notes: [] },
    { value: 8, isFixed: true, rowIndex: 8, colIndex: 6, notes: [] },
    { value: 6, isFixed: true, rowIndex: 8, colIndex: 7, notes: [] },
    { value: 3, isFixed: true, rowIndex: 8, colIndex: 8, notes: [] },
  ],
];

export default mockField;
